spring:
#  devtools:
#    add-properties: true
#    restart:
#      additional-paths: src/main/java

#  mvc:
#    static-path-pattern: /res/**
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB

#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false&serverTimezone=UTC
    username: root
    password: Fb20020722
server:
#  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
